/*===============================================================================
     Table PILOTE : 4 Pilotes
/*===============================================================================*/
INSERT INTO
	PILOTE
		(ID_PILOTE,
		NO_PILOTE,
		NOM,
		PRENOM,
		ADRESSE,
		TELEPHONE)
	VALUES
		(SEQ_ID_PILOTE.NEXTVAL,
		22,
		'LAVIGNE',
		'ROGER',
		'44 DUROCHER',
		'(418)666-3333');
INSERT INTO
	PILOTE
		(ID_PILOTE,
		NO_PILOTE,
		NOM,
		PRENOM,
		ADRESSE,
		TELEPHONE)
	VALUES
		(SEQ_ID_PILOTE.NEXTVAL,
		34,
		'LATRIMOUILLE',
		'ANDRE',
		'5353 MONFORT',
		'(540)555-3344');
INSERT INTO
	PILOTE
		(ID_PILOTE,
		NO_PILOTE,
		NOM,
		PRENOM,
		ADRESSE,
		TELEPHONE)
	VALUES
		(SEQ_ID_PILOTE.NEXTVAL,
		55,
		'LAVERTU',
		'MARIE',
		'5353 MONFORT',
		'(540)555-3344');
INSERT INTO
	PILOTE
		(ID_PILOTE,
		NO_PILOTE,
		NOM,
		PRENOM,
		ADRESSE,
		TELEPHONE)
	VALUES
		(SEQ_ID_PILOTE.NEXTVAL,
		61,
		'GENEST',
		'CLAUDINE',
		'1722 CRESENT, APP 3',
		'(514)555-1234');
/*===============================================================================
     Table AVION : 2 Avions
/*===============================================================================*/
INSERT INTO
	AVION(
		ID_AVION,
		APPEL_AVION,
		NOMBRE_PLACES)
	VALUES
		(SEQ_ID_AVION.NEXTVAL,
		'CADM',
		32);
INSERT INTO
	AVION(
		ID_AVION,
		APPEL_AVION,
		NOMBRE_PLACES)
	VALUES
		(SEQ_ID_AVION.NEXTVAL,
		'COPA',
		48);
/*===============================================================================
     Table AEROPORT : 6 Aeroports
/*===============================================================================*/
INSERT INTO
	AEROPORT(
		ID_AEROPORT,
		ACR_AEROPORT,
		NOM_VILLE)
	VALUES
		(SEQ_ID_AEROPORT.NEXTVAL,
		'QSI',
		'SEPT-ILES');
INSERT INTO
	AEROPORT(
		ID_AEROPORT,
		ACR_AEROPORT,
		NOM_VILLE)
	VALUES
		(SEQ_ID_AEROPORT.NEXTVAL,
		'QGA',
		'GASPE');
INSERT INTO
	AEROPORT(
		ID_AEROPORT,
		ACR_AEROPORT,
		NOM_VILLE)
	VALUES
		(SEQ_ID_AEROPORT.NEXTVAL,
		'QRY',
		'RIMOUSKI');
INSERT INTO
	AEROPORT(
		ID_AEROPORT,
		ACR_AEROPORT,
		NOM_VILLE)
	VALUES
		(SEQ_ID_AEROPORT.NEXTVAL,
		'QBC',
		'BAIE-COMEAU');
INSERT INTO
	AEROPORT(
		ID_AEROPORT,
		ACR_AEROPORT,
		NOM_VILLE)
	VALUES
		(SEQ_ID_AEROPORT.NEXTVAL,
		'QMJ',
		'MONT-JOLI');
INSERT INTO
	AEROPORT(
		ID_AEROPORT,
		ACR_AEROPORT,
		NOM_VILLE)
	VALUES
		(SEQ_ID_AEROPORT.NEXTVAL,
		'QHP',
		'HAVRE SAINT-PIERRE');
/*===============================================================================
     Table VOL : 4 Vols
/*===============================================================================*/
INSERT INTO
	VOL(ID_VOL,
		NO_VOL,
		NOTES)
	VALUES
		(SEQ_ID_VOL.NEXTVAL,
		1822,
		NULL);
INSERT INTO
	VOL(ID_VOL,
		NO_VOL,
		NOTES)
	VALUES
		(SEQ_ID_VOL.NEXTVAL,
		1823,
		NULL);
INSERT INTO
	VOL(ID_VOL,
		NO_VOL,
		NOTES)
	VALUES
		(SEQ_ID_VOL.NEXTVAL,
		1922,
		NULL);
INSERT INTO
	VOL(ID_VOL,
		NO_VOL,
		NOTES)
	VALUES
		(SEQ_ID_VOL.NEXTVAL,
		1923,
		NULL);
/*===============================================================================
     Table SEGMENT : 16 Segments
/*===============================================================================*/
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'A',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		50,
		TO_DATE('06:00', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'B',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		60,
		TO_DATE('07:00', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'C',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		30,
		TO_DATE('08:00', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'D',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1822),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		40,
		TO_DATE('09:00', 'HH24:MI'));

INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'A',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		40,
		TO_DATE('17:00', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'B',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		35,
		TO_DATE('18:00', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'C',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		55,
		TO_DATE('19:00', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'D',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1823),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		45,
		TO_DATE('20:00', 'HH24:MI'));

INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'A',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		50,
		TO_DATE('17:30', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'B',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		60,
		TO_DATE('18:30', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'C',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		30,
		TO_DATE('19:30', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'D',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1922),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		40,
		TO_DATE('20:30', 'HH24:MI'));

INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'A',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QHP'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		40,
		TO_DATE('05:30', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'B',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QGA'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		35,
		TO_DATE('06:30', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'C',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QSI'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		55,
		TO_DATE('07:30', 'HH24:MI'));
INSERT INTO
	SEGMENT(
		ID_SEGMENT,
		ORDRE_SEGMENT,
		ID_VOL,
		AEROPORT_DEPART,
		AEROPORT_DESTINATION,
		DUREE_VOL,
		HEURE_DEPART
		)
	VALUES
		(
		SEQ_ID_SEGMENT.NEXTVAL,
		'D',
		(SELECT ID_VOL FROM VOL WHERE NO_VOL = 1923),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QBC'),
		(SELECT ID_AEROPORT FROM AEROPORT WHERE ACR_AEROPORT = 'QMJ'),
		45,
		TO_DATE('08:30', 'HH24:MI'));
/*===============================================================================
     Table ENVOLEE : 128 Envolées
/*===============================================================================*/
INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-13', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-14', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-15', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-16', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-17', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-18', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-19', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-20', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));