/***********************************************************
	PL SQL FONCTION/PROCÉDURES
	Schéma MRD:	"NordAir"
	Auteur:		Dominique Septembre + Charles-Edouard Beaudet - Cégep de Ste-Foy  	
***********************************************************/

/***********************************************************
Fonction pour convertir les minutes (numéric) en hh:mm
***********************************************************/
SHOW ERRORS FUNCTION FORMAT_NUMERIC_TO_HOUR;

CREATE OR REPLACE
	FUNCTION FORMAT_NUMERIC_TO_HOUR(P_NUMERIC IN NUMERIC) RETURN VARCHAR2
AS
	V_MINUTES NUMERIC;	
	V_HOURS NUMERIC;
	V_FORMAT_HOURS VARCHAR2(5);
BEGIN
	V_MINUTES := MOD(P_NUMERIC, 60);
	V_HOURS := TRUNC(P_NUMERIC / 60, 0);
	IF(V_HOURS < 10) THEN
		V_FORMAT_HOURS := '0' || V_HOURS || ':';
	ELSE
		V_FORMAT_HOURS := V_HOURS || ':';
	END IF;
	IF(V_MINUTES < 10) THEN
		V_FORMAT_HOURS := V_FORMAT_HOURS || '0' || V_MINUTES;
	ELSE
		V_FORMAT_HOURS := V_FORMAT_HOURS || V_MINUTES;
	END IF;
	RETURN V_FORMAT_HOURS;	
END FORMAT_NUMERIC_TO_HOUR;
/

SELECT FORMAT_NUMERIC_TO_HOUR(1453) FROM DUAL;

/*****************************************************************
Fonction pour avoir le nombre de places disponibles d'un vol
******************************************************************/
SHOW ERRORS FUNCTION GET_NUMBER_OF_OCCUPIED_PLACE;

CREATE OR REPLACE
	FUNCTION GET_NUMBER_OF_OCCUPIED_PLACE(P_ID_VOL IN NUMERIC, P_DATE_VOL IN VARCHAR2) RETURN NUMERIC
AS
	V_OCCUPIED NUMERIC;
BEGIN
	SELECT
		NVL(MAX(COUNT(RESERVATION_ENVOLEE.CODE_SIEGE)), 0) AS "SIEGE"
	INTO
		V_OCCUPIED
	FROM 
		SEGMENT
			INNER JOIN ENVOLEE
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN RESERVATION_ENVOLEE
						ON ENVOLEE.ID_ENVOLEE = RESERVATION_ENVOLEE.ID_ENVOLEE
	WHERE 
		SEGMENT.ID_VOL = P_ID_VOL AND
		TO_CHAR(ENVOLEE.DATE_ENVOLEE,'DD-MM-YYYY') = P_DATE_VOL
	GROUP BY
		SEGMENT.ORDRE_SEGMENT;
	RETURN V_OCCUPIED
END GET_NUMBER_OF_OCCUPIED_PLACE;
/

SELECT GET_NUMBER_OF_OCCUPIED_PLACE(2, '14-05-2015') FROM DUAL;

/*****************************************************************
SELECT pour avoir les informations d'un vol
******************************************************************/	
SELECT 
	SEGMENT.ID_VOL AS "VOL",
	VOL.NO_VOL AS "NO VOL",
	SEGMENT.ID_SEGMENT AS "SEGMENT",
	SEGMENT.ORDRE_SEGMENT AS "ORDRE",
	ENVOLEE.ID_ENVOLEE AS "ENVOLEE",
	TO_CHAR(ENVOLEE.DATE_ENVOLEE,'DD-MM-YYYY') AS "DATE",
	RESERVATION_ENVOLEE.ID_RESERV_ENVOLEE AS "RESERV ENVOLEE",
	RESERVATION_ENVOLEE.CODE_SIEGE AS "SIEGE"
FROM 
	SEGMENT
		FULL OUTER JOIN ENVOLEE
			ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
				FULL OUTER JOIN RESERVATION_ENVOLEE
					ON ENVOLEE.ID_ENVOLEE = RESERVATION_ENVOLEE.ID_ENVOLEE
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
ORDER BY
	SEGMENT.ID_VOL,
	ENVOLEE.DATE_ENVOLEE,
	SEGMENT.ORDRE_SEGMENT;
	
SELECT 
	ENVOLEE.ID_SEGMENT AS "ORDRE",
FROM
	PASSAGER
		INNER JOIN RESERVATION
			ON PASSAGER.ID_PASSAGER = RESERVATION.ID_PASSAGER
				INNER JOIN RESERVATION_ENVOLEE
					ON RESERVATION_ENVOLEE.ID_RESERVATION = RESERVATION.ID_RESERVATION
						INNER JOIN ENVOLEE
							ON RESERVATION_ENVOLEE.ID_ENVOLEE = ENVOLEE.ID_ENVOLEE
						