/* **********************************************************
	DDL Drop
	Schéma MRD:	"NordAir"
	Auteur:		Dominique Septembre & Charles-Edouard Beaudet - Cégep de Ste-Foy  	
***********************************************************/
/*
	Suppression des tables, séquences et indexs
*/
DROP INDEX IDX_PASSAGER;
DROP INDEX IDX_PILOTE;
DROP INDEX IDX_SEGMENT;
DROP INDEX IDX_ENVOLEE;
DROP TABLE RESERVATION_ENVOLEE;
DROP TABLE ENVOLEE;
DROP TABLE PILOTE;
DROP TABLE SEGMENT;
DROP TABLE VOL;
DROP TABLE AEROPORT;
DROP TABLE AVION;
DROP TABLE RESERVATION;
DROP TABLE PASSAGER;
DROP SEQUENCE SEQ_ID_RESERVATION;
DROP SEQUENCE SEQ_ID_RESERV_ENVOLEE;
DROP SEQUENCE SEQ_ID_ENVOLEE;
DROP SEQUENCE SEQ_ID_PILOTE;
DROP SEQUENCE SEQ_ID_SEGMENT;
DROP SEQUENCE SEQ_ID_VOL;
DROP SEQUENCE SEQ_ID_AEROPORT;
DROP SEQUENCE SEQ_ID_AVION;
DROP SEQUENCE SEQ_ID_PASSAGER;