/*===========================================================
	DML Inserts Envolee
	Schéma MRD:	"NordAir"
	Auteur:		Dominique Septembre & Charles-Edouard Beaudet - Cégep de Ste-Foy  	
===========================================================*/

/*===============================================================================
     Table ENVOLEE : 128 Envolées
/*===============================================================================*/
INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-13', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-14', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-15', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-16', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-17', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-18', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-19', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));

INSERT INTO
	ENVOLEE
	(
		ID_ENVOLEE,
		DATE_ENVOLEE,
		ID_SEGMENT,
		ID_AVION,
		ID_PILOTE
		)
SELECT 
	SEQ_ID_ENVOLEE.NEXTVAL,
	TO_DATE('2015-05-20', 'yyyy-mm-dd') AS JOUR,
	SEGMENT.ID_SEGMENT,
	AVION.ID_AVION,
	PILOTE.ID_PILOTE
FROM AVION
	CROSS JOIN PILOTE
	CROSS JOIN SEGMENT
		INNER JOIN VOL
			ON SEGMENT.ID_VOL = VOL.ID_VOL
WHERE
	((VOL.NO_VOL = '1822' OR VOL.NO_VOL = '1823')
	AND (PILOTE.NO_PILOTE = '55' AND AVION.APPEL_AVION = 'COPA'))
	OR
	((VOL.NO_VOL = '1922' OR VOL.NO_VOL = '1923')
	AND (PILOTE.NO_PILOTE = '22' AND AVION.APPEL_AVION = 'CADM'));