/***********************************************************
	PL SQL FONCTION/PROCÉDURES
	Schéma MRD:	"NordAir"
	Auteur:		Dominique Septembre + Charles-Edouard Beaudet - Cégep de Ste-Foy  	
***********************************************************/

/***********************************************************
Fonction pour convertir les minutes (numéric) en hh:mm
***********************************************************/
SHOW ERRORS FUNCTION FORMAT_NUMERIC_TO_HOUR;

CREATE OR REPLACE
	FUNCTION FORMAT_NUMERIC_TO_HOUR(P_NUMERIC IN NUMERIC) RETURN VARCHAR2
AS
	V_MINUTES NUMERIC;	
	V_HOURS NUMERIC;
	V_FORMAT_HOURS VARCHAR2(5);
BEGIN
	V_MINUTES := MOD(P_NUMERIC, 60);
	V_HOURS := TRUNC(P_NUMERIC / 60, 0);
	IF(V_HOURS < 10) THEN
		V_FORMAT_HOURS := '0' || V_HOURS || ':';
	ELSE
		V_FORMAT_HOURS := V_HOURS || ':';
	END IF;
	IF(V_MINUTES < 10) THEN
		V_FORMAT_HOURS := V_FORMAT_HOURS || '0' || V_MINUTES;
	ELSE
		V_FORMAT_HOURS := V_FORMAT_HOURS || V_MINUTES;
	END IF;
	RETURN V_FORMAT_HOURS;	
END FORMAT_NUMERIC_TO_HOUR;
/

SELECT FORMAT_NUMERIC_TO_HOUR(1453) FROM DUAL;

/*****************************************************************
Fonction pour avoir le nombre de places occupées d'un segment
******************************************************************/
SHOW ERRORS FUNCTION GET_NUMBER_OF_OCCUPIED_PLACE;

CREATE OR REPLACE
	FUNCTION GET_NUMBER_OF_OCCUPIED_PLACE(P_ID_ENVOLEE IN NUMERIC) RETURN NUMERIC
AS
	V_ENVOL_RESERV NUMERIC;
BEGIN
	SELECT COUNT(*) INTO V_ENVOL_RESERV FROM RESERVATION_ENVOLEE WHERE ID_ENVOLEE = P_ID_ENVOLEE GROUP BY ID_ENVOLEE;
	RETURN V_ENVOL_RESERV;
END GET_NUMBER_OF_OCCUPIED_PLACE;
/

SELECT GET_NUMBER_OF_OCCUPIED_PLACE(9) FROM DUAL;

/*****************************************************************
Fonction pour avoir le nombre de places disponibles d'un vol
******************************************************************/
SHOE ERRORS FUNCTION GET_NUMBER_OF_AVAILABLE_PLACE;

CREATE OR REPLACE
	FUNCTION GET_NUMBER_OF_AVAILABLE_PLACE(P_ID_VOL IN NUMERIC) RETURN NUMERIC
AS
	V_OCCUPIED NUMERIC;
	V_AVAILABLE NUMERIC;
BEGIN
	SELECT COUNT(*) INTO V_OCCUPIED FROM (SELECT DISTINCT
												RESERVATION_ENVOLEE.CODE_SIEGE
											FROM 
												RESERVATION_ENVOLEE
													INNER JOIN ENVOLEE
														ON RESERVATION_ENVOLEE.ID_ENVOLEE = ENVOLEE.ID_ENVOLEE
															INNER JOIN SEGMENT
																ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
											WHERE
												SEGMENT.ID_VOL = P_ID_VOL);
	SELECT DISTINCT
		AVION.NOMBRE_PLACES
	INTO
		V_AVAILABLE
	FROM 
		AVION 
			INNER JOIN ENVOLEE 
				ON AVION.ID_AVION = ENVOLEE.ID_AVION
					INNER JOIN SEGMENT
						ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
	WHERE
		SEGMENT.ID_VOL = P_ID_VOL;
	RETURN V_AVAILABLE - V_OCCUPIED;
END GET_NUMBER_OF_AVAILABLE_PLACE;
/

SELECT GET_NUMBER_OF_AVAILABLE_PLACE(2) FROM DUAL;

/*****************************************************************
SELECT pour avoir les informations d'un vol
******************************************************************/
SELECT
	SEGMENT.ID_VOL,
	SEGMENT.ID_SEGMENT,
	ENVOLEE.ID_ENVOLEE,
	ENVOLEE.ID_AVION,
	RESERVATION_ENVOLEE.ID_RESERVATION,
	RESERVATION_ENVOLEE.ID_RESERV_ENVOLEE,
	SEGMENT.ID_SEGMENT,
	RESERVATION_ENVOLEE.CODE_SIEGE,
	ENVOLEE.DATE_ENVOLEE
FROM 
	RESERVATION_ENVOLEE
		INNER JOIN ENVOLEE
			ON RESERVATION_ENVOLEE.ID_ENVOLEE = ENVOLEE.ID_ENVOLEE
				INNER JOIN SEGMENT
					ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
WHERE
	SEGMENT.ID_VOL = 2
ORDER BY
	SEGMENT.ID_VOL,
	SEGMENT.ID_SEGMENT,
	ENVOLEE.ID_ENVOLEE,
	RESERVATION_ENVOLEE.CODE_SIEGE;
