/***********************************************************
	PL SQL FONCTION/PROCÉDURES
	Schéma MRD:	"NordAir"
	Auteur:		Dominique Septembre + Charles-Edouard Beaudet - Cégep de Ste-Foy  	
***********************************************************/

/***********************************************************
Fonction pour convertir les minutes (numéric) en hh:mm
***********************************************************/
SHOW ERRORS FUNCTION FORMAT_NUMERIC_TO_HOUR;

CREATE OR REPLACE
	FUNCTION FORMAT_NUMERIC_TO_HOUR(P_NUMERIC IN NUMERIC) RETURN VARCHAR2
AS
	V_MINUTES NUMERIC;	
	V_HOURS NUMERIC;
	V_FORMAT_HOURS VARCHAR2(5);
BEGIN
	V_MINUTES := MOD(P_NUMERIC, 60);
	V_HOURS := TRUNC(P_NUMERIC / 60, 0);
	IF(V_HOURS < 10) THEN
		V_FORMAT_HOURS := '0' || V_HOURS || ':';
	ELSE
		V_FORMAT_HOURS := V_HOURS || ':';
	END IF;
	IF(V_MINUTES < 10) THEN
		V_FORMAT_HOURS := V_FORMAT_HOURS || '0' || V_MINUTES;
	ELSE
		V_FORMAT_HOURS := V_FORMAT_HOURS || V_MINUTES;
	END IF;
	RETURN V_FORMAT_HOURS;	
END FORMAT_NUMERIC_TO_HOUR;
/

SELECT FORMAT_NUMERIC_TO_HOUR(1453) FROM DUAL;

/*****************************************************************
Fonction pour avoir le nombre de places disponibles d'un segment
******************************************************************/
SHOW ERRORS FUNCTION GET_NUMBER_OF_AVAILABLE_PLACE;

CREATE OR REPLACE
	FUNCTION GET_NUMBER_OF_AVAILABLE_PLACE(P_ID_ENVOLEE IN NUMERIC) RETURN NUMERIC
AS
	V_VOL_RESERV NUMERIC;
	V_AVION_PLACES NUMERIC;
BEGIN
	SELECT COUNT(*) INTO V_VOL_RESERV FROM RESERVATION_ENVOLEE WHERE ID_ENVOLEE = P_ID_ENVOLEE GROUP BY ID_ENVOLEE;
	SELECT AVION.NOMBRE_PLACES INTO V_AVION_PLACES FROM AVION INNER JOIN ENVOLEE ON AVION.ID_AVION = ENVOLEE.ID_AVION WHERE ENVOLEE.ID_ENVOLEE = P_ID_ENVOLEE;
	RETURN V_AVION_PLACES - V_VOL_RESERV;
END GET_NUMBER_OF_AVAILABLE_PLACE;
/

SELECT GET_NUMBER_OF_AVAILABLE_PLACE(9) FROM DUAL;