/* **********************************************************
	Script DML  : peuplement des tables PASSAGER, RESERVATION et RESERVATION_ENVOLEE
				  PARTIE 1
	Fichier MRD : "NordAir" VERSION 2
	Auteur	    : Sylvie Monjal 
				  Département d'informatique
				  Cégep de Sainte-Foy
********************************************************** */

/* AVANT L'EXÉCUTION DE CE SCRIPT No 1:
	- ASSUREZ-VOUS D'AVOIR PEUPLÉ LES AUTRES TABLES DE LA BD:
			- AEROPORT, VOL, SEGMENT, PILOTE, AVION, ENVOLEE
			- EN CONFORMITÉ AVEC LES DONNÉES DE L'ÉNONCÉ.
	- ASSUREZ-VOUS DE RÉINITIALISER LES SÉQUENCES (DROP-CREATE):
			SEQ_ID_PASSAGER, SEQ_ID_RESERVATION et SEQ_ID_RESERV_ENVOLEE */

/* APRÈS L'EXÉCUTION DE CE SCRIPT No 1:
	- N'OUBLIEZ PAS DE FAIRE UN COMMIT
	- EXÉCUTEZ LE SCRIPT "NordAir2DMLInsertTReservation2.sql" */
	


SAVEPOINT RESERVATION1;
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Barbeau',
		 'Isabelle', 
		 '4545 St-Jules',
		 '(418)555-3233' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-04-13','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822;
-- 
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Berthiaume',
		 'Jonny', 
		 '1100 Rene',
		 '(418)555-3222' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-04-18','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '02B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '03C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1823;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Bolduc',
		 'Sebastien', 
		 '1234 Germain',
		 '(418)555-3244' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-04-22','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '04D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'BrindAmour',
		 'Jean-Francois', 
		 '33 Royale',
		 '(418)555-5533' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-04-11','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '05A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '06B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-14', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1923;
---          
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Desjardins',
		 'Francois', 
		 '10225 St-Laurent',
		 '(418)555-4633' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-04-20','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1822;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1822;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '07A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-16', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-16', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1923;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '04C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-16', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '04D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-17', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1923;
--
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Cote',
		 'Mathieu', 
		 '2020 Levesque',
		 '(418)555-5678' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-01','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '02A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-15', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922;
---     
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Fortin',
		 'Jean-Philippe', 
		 '4440 Elzear',
		 '(418)555-3567' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-01','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '08A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-16', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '03A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-16', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Harnois',
		 'Stephane J.', 
		 '12a duFort',
		 '(418)555-3255' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-01','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-14', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Fortin',
		 'Mathieu', 
		 '1223 Jeanne d''Arc',
		 '(418)555-4563' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-02','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '03C'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		(SEGMENT.ORDRE_SEGMENT = 'A' OR SEGMENT.ORDRE_SEGMENT = 'B')
		AND
		VOL.NO_VOL = 1923;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-15', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1922;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '08A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-15', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '06B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-16', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Jobin',
		 'Samuel', 
		 '445 St-Cyrille',
		 '(418)555-3786' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-03','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-16', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1823;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Ratte',
		 'Francois', 
		 '1024 Principale',
		 '(418)555-9876' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-04','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-17', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1923;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '09D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-18', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1822;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Gregoire',
		 'Pierre-Luc', 
		 '4040 Beausejour',
		 '(418)555-0987' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-05','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '07D'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT IN ('A','B','C')
		AND
		VOL.NO_VOL = 1923;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-18', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822;
---     
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Dostie-Proulx',
		 'Pierre-Luc', 
		 '22 Dupont',
		 '(418)555-1231' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-06','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-18', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1823;
---
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Nadeau',
		 'Michel', 
		 '123 Albert',
		 '(418)555-8765' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-05','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'D'
		AND
		VOL.NO_VOL = 1922;
--- 
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Tremblay',
		 'Vincent', 
		 '9856 St-Louis',
		 '(418)555-6935' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-04','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923;
---  
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Mercier',
		 'David', 
		 '4850 duRoy',
		 '(418)555-8700' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-03','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-13', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1822;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-20', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'C'
		AND
		VOL.NO_VOL = 1923;
---    
INSERT INTO
	PASSAGER
		(ID_PASSAGER,
		 NOM,
		 PRENOM,
		 ADRESSE,
		 TELEPHONE)
	VALUES
		(SEQ_ID_PASSAGER.NEXTVAL, 
		 'Dionne',
		 'Marjorie', 
		 '3654D duCarre',
		 '(418)555-3267' );      
INSERT INTO
	RESERVATION
		(ID_RESERVATION,
		 DATE_RESERVATION,
		 ID_PASSAGER)
	VALUES
		(SEQ_ID_RESERVATION.NEXTVAL,
		 TO_DATE('2015-05-02','yyyy-mm-dd'),
		 SEQ_ID_PASSAGER.CURRVAL);
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '01A'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-18', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'A'
		AND
		VOL.NO_VOL = 1922;
INSERT INTO
	RESERVATION_ENVOLEE
		(ID_RESERV_ENVOLEE,
		 ID_RESERVATION,
		 ID_ENVOLEE,
		 CODE_SIEGE)
	SELECT
		 SEQ_ID_RESERV_ENVOLEE.NEXTVAL,
		 SEQ_ID_RESERVATION.CURRVAL,
		 ENVOLEE.ID_ENVOLEE,
		 '06B'
	FROM
		ENVOLEE
			INNER JOIN SEGMENT
				ON ENVOLEE.ID_SEGMENT = SEGMENT.ID_SEGMENT
					INNER JOIN VOL
						ON SEGMENT.ID_VOL = VOL.ID_VOL
	WHERE
		ENVOLEE.DATE_ENVOLEE = TO_DATE('2015-05-20', 'yyyy-mm-dd')
		AND
		SEGMENT.ORDRE_SEGMENT = 'B'
		AND
		VOL.NO_VOL = 1922;